--drop table friends,comments,photos,clients

CREATE TABLE clients (
  client_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
  first_name varchar(50) NOT NULL,
  last_name varchar(50) NOT NULL,
  email varchar UNIQUE NOT NULL, 
  password varchar NOT NULL CHECK (password ~ '^(?=.*[A-Za-z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,}$')
);
CREATE TABLE photos (
  photo_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
  client_id integer NOT NULL,
  title varchar(60),
  file_location varchar(150) NOT NULL,
  permissions varchar(8) NOT NULL CHECK("permissions" IN ('all', 'private', 'friendly'))
);
CREATE TABLE comments (
  comment_id integer GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
  photo_id integer NOT NULL,
  client_id integer NOT NULL,
  comment_text varchar,
  created_at timestamp with time ZONE DEFAULT NOW()
);
CREATE TABLE friends (
  client_id integer NOT NULL,
  friend_id integer NOT NULL,
  PRIMARY KEY (client_id, friend_id)
);
ALTER TABLE photos ADD FOREIGN KEY (client_id) REFERENCES clients (client_id);
ALTER TABLE comments ADD FOREIGN KEY (client_id) REFERENCES clients (client_id);
ALTER TABLE comments ADD FOREIGN KEY (photo_id) REFERENCES photos (photo_id);
ALTER TABLE friends ADD FOREIGN KEY (client_id) REFERENCES clients (client_id);
ALTER TABLE friends ADD FOREIGN KEY (friend_id) REFERENCES clients (client_id);
